
### 通过id查询
GET http://localhost:5051/components/1

### 添加
POST http://localhost:5051/components
Content-Type: application/json

{
  "id": null,
  "name": "insertName"
}

### 删除
DELETE http://localhost:5051/components/10

### 分页查询
GET http://localhost:5051/components/0/5
Content-Type: application/json

{
  "id": 1,
  "name": null
}

### 修改
PUT http://localhost:5051/components
Content-Type: application/json

{
  "id": 2,
  "name": "changedName"
}
