server:
  port: ${port:1011}
logging:
  level:
    com.woniuxy.storehousemanage: debug
spring:
  application:
    name: storehouse-manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noby_computermall?serverTimezone=UTC
    username: root
    password: 123
  cloud:
    nacos:
      server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: fsp_tx_group

mybatis:
  type-aliases-package: com.woniuxy.commonentity.entity
  mapper-locations: classpath:/mapper/*Dao.xml


