
### 通过id查询
GET http://localhost:4041/saleOrder/1

### 添加
POST http://localhost:4041/saleOrder
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}


### 删除
DELETE http://localhost:4041/saleOrder/1

### 分页查询
GET http://localhost:4041/saleOrder/2/5
Content-Type: application/json

{
  "id": null,
  "address": null,
  "num": 1,
  "totalCapacity": 300,
  "componentsId": 1
}

### 修改
PUT http://localhost:4041/saleOrder
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}
