server:
  port: ${port:7071}
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      globalcors: #跨域
        add-to-simple-url-handler-mapping: true   #针对OPTION跨域运行
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders: "*"               #允许请求头
      routes: #路由配置Q
        - id: sales-manage
          uri: lb://sales-manage
          predicates:
            - Path=/client/**,/clientAddress/**,/saleCart/**,/saleCartOrderItem/**,/saleOrder/**,/saleRecord/**
        - id: cooperation-manage
          uri: lb://cooperation-manage
          predicates:
            - Path=/components/**,/model/**,/supplier/**
        - id: storehouse-manage
          uri: lb://storehouse-manage
          predicates:
            - Path=/store/**,/storeRecord/**