
### 下单
GET http://localhost:7071/saleOrder/placeOrder/2

### 付款
GET http://localhost:7071/saleOrder/payOrder/2

### 发货
GET http://localhost:7071/saleOrder/shipOrder/2

### 收货
GET http://localhost:7071/saleOrder/receiveOrder/2

### 通过id查询
GET http://localhost:7071/saleOrder/1

### 添加
POST http://localhost:7071/saleOrder
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}


### 删除
DELETE http://localhost:7071/saleOrder/1

### 分页查询
GET http://localhost:7071/saleOrder/2/5
Content-Type: application/json

{
  "id": null,
  "address": null,
  "num": 1,
  "totalCapacity": 300,
  "componentsId": 1
}

### 修改
PUT http://localhost:7071/saleOrder
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}
