
### 通过id查询
GET http://localhost:7071/store/1

### 添加
POST http://localhost:7071/store
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}


### 删除
DELETE http://localhost:7071/store/1

### 分页查询
GET http://localhost:7071/store/2/5
Content-Type: application/json

{
  "id": null,
  "address": null,
  "num": 1,
  "totalCapacity": 300,
  "componentsId": 1
}

### 修改
PUT http://localhost:7071/store
Content-Type: application/json

{
  "id": 1,
  "componentsId": null,
  "address": null,
  "num": 400,
  "totalCapacity": null
}
