
### 通过id查询
GET http://localhost:7071/supplier/1

### 添加
POST http://localhost:7071/supplier
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}


### 删除
DELETE http://localhost:7071/supplier/1

### 分页查询
GET http://localhost:7071/supplier/2/5
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}

### 修改
PUT http://localhost:7071/supplier
Content-Type: application/json

{
  "id": null,
  "name": null,
  "componentsId": 1
}
