server:
  port: ${port:5051}
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    com.woniuxy.cooperationmanage: debug
spring:
  application:
    name: cooperation-manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/noby_computermall?serverTimezone=UTC
    username: root
    password: 123
  cloud:
    nacos:
      server-addr: localhost:8848
#    alibaba:
#      seata:
#        tx-service-group: fsp_tx_group
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-server
      username: nacos
      password: nacos
  tx-service-group: seata-demo # 事务组名称
  service:
    vgroup-mapping: # 事务组与cluster的映射关系
      seata-demo: default
  data-source-proxy-mode: AT
mybatis:
  type-aliases-package: com.woniuxy.commonentity.entity
  mapper-locations: classpath:/mapper/*Dao.xml


